// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRmcu80MmOuBfPmRYxfuy-GO1_Ue0-fg',
    appId: '1:747258352161:web:dd77e892dc14b8edad4960',
    messagingSenderId: '747258352161',
    projectId: 'rigel-9d30c',
    authDomain: 'rigel-9d30c.firebaseapp.com',
    storageBucket: 'rigel-9d30c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXQqwq50SACfur0oLC-Gt4AYvNjBJuJlo',
    appId: '1:747258352161:android:783a108dd559ecd0ad4960',
    messagingSenderId: '747258352161',
    projectId: 'rigel-9d30c',
    storageBucket: 'rigel-9d30c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdROeT3Z9oFsEq-l5pUmLRrTKXLsmFrdg',
    appId: '1:747258352161:ios:c6f3abc9121f940cad4960',
    messagingSenderId: '747258352161',
    projectId: 'rigel-9d30c',
    storageBucket: 'rigel-9d30c.firebasestorage.app',
    iosBundleId: 'com.example.rigelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdROeT3Z9oFsEq-l5pUmLRrTKXLsmFrdg',
    appId: '1:747258352161:ios:c6f3abc9121f940cad4960',
    messagingSenderId: '747258352161',
    projectId: 'rigel-9d30c',
    storageBucket: 'rigel-9d30c.firebasestorage.app',
    iosBundleId: 'com.example.rigelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDRmcu80MmOuBfPmRYxfuy-GO1_Ue0-fg',
    appId: '1:747258352161:web:c6d913d2b8468760ad4960',
    messagingSenderId: '747258352161',
    projectId: 'rigel-9d30c',
    authDomain: 'rigel-9d30c.firebaseapp.com',
    storageBucket: 'rigel-9d30c.firebasestorage.app',
  );
}
